# Built with Jekyll 4.3.4

# Setup
title:               doggEd.
tagline:             'a jekyll theme for bilingual minimal editions'
description:         ''
url:                 'https://cboucher01.github.io'
baseurl:             '/dogged'
chapter-menu:        true # Set to true if you want the sidebar chapter menu to appear

languages: # doggEd currently supports up to two languages
  - name: English # Full name of primary/default language (e.g. "English")
    code: en # ISO 639 code for primary language (e.g. "en")
  - name: Spanish # Full name of secondary language
    code: sp # ISO 639 code for secondary language

# About/contact
author:
  name:              Cameron Boucher
  url:               https://github.io/cboucher01
  email:             

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for raw texts and rendered chapters
collections:
  texts:
    output: false
  chapters:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
